- name: a10_cgnv6_nat_shared_pool_group example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Create a10_cgnv6_nat_shared_pool_group
    a10_cgnv6_nat_shared_pool_group:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      a10_port: "{{ a10_port }}"
      a10_protocol: "{{ a10_protocol }}"
      partition: "MyPartition"
      members: 
        uuid: "Nat_shared_pool"
