- name: a10_cgnv6_nat_pool_group example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Create a10_cgnv6_nat_pool_group
    a10_cgnv6_nat_pool_group:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      a10_port: "{{ a10_port }}"
      a10_protocol: "{{ a10_protocol }}"
      partition: "shared"
      member_list:
        - pool_name: "CGN_Dynamic"
      pool_group_name: "CGN_Dynamic_Pool_Group"
      vrid: "0"
