- name: a10_cgnv6_nat_exclude_port_tcp example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Create a10_cgnv6_nat_exclude_port_tcp
    a10_cgnv6_nat_exclude_port_tcp:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      a10_port: "{{ a10_port }}"
      a10_protocol: "{{ a10_protocol }}"
      port_list: 
        - port: "9000"
          port_end: "9010"
