- name: a10_cgnv6_nat_pool example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Create a10_cgnv6_nat_pool
    a10_cgnv6_nat_pool:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      a10_port: "{{ a10_port }}"
      a10_protocol: "{{ a10_protocol }}"
      pool_name: "CGN_Dynamic"
      start_address: "192.0.2.11"
      end_address: "192.0.2.12"
      netmask: "/28"
      vrid: "0" 
      partition: "shared"
      max_users_per_ip: "10"
      shared: "true"
