- name: a10_cgnv6_nat_icmpv6 example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Create a10_cgnv6_nat_icmpv6
    a10_cgnv6_nat_icmpv6:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      a10_port: "{{ a10_port }}"
      a10_protocol: "{{ a10_protocol }}"
      partition: "shared"
      respond_to_ping: "true"
