- name: Change Boot Image example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: a10_bootimage instance
    a10_bootimage:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      a10_port: "{{ a10_port }}"
      a10_protocol: "{{ a10_protocol }}"
      hd_cfg:
        pri: 1
        sec: 1
        hd: 1
