- name: a10_cgnv6_nat64_global example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Create a10_cgnv6_nat64_global
    a10_cgnv6_nat64_global:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      a10_port: "{{ a10_port }}"
      a10_protocol: "{{ a10_protocol }}"
      user_quota_prefix_length: "128"
      sampling_enable:
        - counters1: "all"
          counters2: "h323_alg_no_quota"
          counters3: "nat_pool_force_delete"
      icmp:
        send_on_user_quota_exceeded: "host-unreachable"
        send_on_port_unavailable: "host-unreachable"
