- name: a10_cgnv6_fixed_nat_global example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Create a10_cgnv6_fixed_nat_global
    a10_cgnv6_fixed_nat_global:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      a10_port: "{{ a10_port }}"
      a10_protocol: "{{ a10_protocol }}"
      create_port_mapping_file: "1"
      sampling_enable:
        - counters1: "all"
          counters2: "nat44-udp-alg-fullcone-freed-shadow"
          counters3: "fnat44_fwd_egress_pkt_size_range1"
          #          counters4: "fnatdslite_fwd_ingress_pkt_size_range2"
      port_mapping_files_count: "0"
