- name: a10_cgnv6_fixed_nat_full_cone_session Example PlayBook
  hosts: localhost
  connection: local
  tasks:
  - name: a10_cgnv6_fixed_nat_full_cone_session
    a10_cgnv6_fixed_nat_full_cone_session:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      a10_port: "{{ a10_port }}"
      a10_protocol: "{{ a10_protocol }}"
      partition: "MyPartition"
