

- name: Create a10_vrrp_a_vrid_lead example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Create a10_vrrp_a_vrid_lead instance
    a10_vrrp_a_vrid_lead:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      vrid_lead_str: default-vrid-lead

- name: Update a10_vrrp_a_vrid_lead example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Update a10_vrrp_a_vrid_lead instance
    a10_vrrp_a_vrid_lead:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      state: present
      vrid_lead_str: default-vrid-lead

- name: Delete a10_vrrp_a_vrid_lead example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Delete a10_vrrp_a_vrid_lead instance
    a10_vrrp_a_vrid_lead:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      state: absent
      vrid_lead_str: default-vrid-lead