

- name: Create a10_vrrp_a_interface_trunk example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Create a10_vrrp_a_interface_trunk instance
    a10_vrrp_a_interface_trunk:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      trunk_val: 1

- name: Update a10_vrrp_a_interface_trunk example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Update a10_vrrp_a_interface_trunk instance
    a10_vrrp_a_interface_trunk:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      state: present
      trunk_val: 1

- name: Delete a10_vrrp_a_interface_trunk example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Delete a10_vrrp_a_interface_trunk instance
    a10_vrrp_a_interface_trunk:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      state: absent
      trunk_val: 1