

- name: Create a10_slb_template_ssli example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Create a10_slb_template_ssli instance
    a10_slb_template_ssli:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      name: my_ssli
      type: http

- name: Update a10_slb_template_ssli example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Update a10_slb_template_ssli instance
    a10_slb_template_ssli:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      state: present
      name: my_ssli
      type: http

- name: Delete a10_slb_template_ssli example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Delete a10_slb_template_ssli instance
    a10_slb_template_ssli:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      state: absent
      name: my_ssli
      type: http