

- name: Create a10_slb_template_sip example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Create a10_slb_template_sip instance
    a10_slb_template_sip:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      name: my_sip
      pstn_gw: pstn
      interval: 5
      timeout: 1

- name: Update a10_slb_template_sip example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Update a10_slb_template_sip instance
    a10_slb_template_sip:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      state: present
      name: my_sip
      pstn_gw: pstn
      interval: 5
      timeout: 1

- name: Delete a10_slb_template_sip example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Delete a10_slb_template_sip instance
    a10_slb_template_sip:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      state: absent
      name: my_sip
      pstn_gw: pstn
      interval: 5
      timeout: 1