

- name: Create a10_slb_template_udp example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Create a10_slb_template_udp instance
    a10_slb_template_udp:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      name: default
      idle_timeout: 1
      stateless_conn_timeout: 5

- name: Update a10_slb_template_udp example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Update a10_slb_template_udp instance
    a10_slb_template_udp:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      state: present
      name: default
      idle_timeout: 1
      stateless_conn_timeout: 5

- name: Delete a10_slb_template_udp example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Delete a10_slb_template_udp instance
    a10_slb_template_udp:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      state: absent
      name: default
      idle_timeout: 1
      stateless_conn_timeout: 5