

- name: Create a10_slb_template_fix example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Create a10_slb_template_fix instance
    a10_slb_template_fix:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      name: my_fix

- name: Update a10_slb_template_fix example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Update a10_slb_template_fix instance
    a10_slb_template_fix:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      state: present
      name: my_fix

- name: Delete a10_slb_template_fix example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Delete a10_slb_template_fix instance
    a10_slb_template_fix:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      state: absent
      name: my_fix