

- name: Create a10_slb_template_smpp example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Create a10_slb_template_smpp instance
    a10_slb_template_smpp:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      name: my_smpp
      server_enquire_link_val: 5

- name: Update a10_slb_template_smpp example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Update a10_slb_template_smpp instance
    a10_slb_template_smpp:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      state: present
      name: my_smpp
      server_enquire_link_val: 5

- name: Delete a10_slb_template_smpp example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Delete a10_slb_template_smpp instance
    a10_slb_template_smpp:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      state: absent
      name: my_smpp
      server_enquire_link_val: 5