

- name: Create a10_slb_template_dns example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Create a10_slb_template_dns instance
    a10_slb_template_dns:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      name: my_dns
      default_policy: nocache

- name: Update a10_slb_template_dns example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Update a10_slb_template_dns instance
    a10_slb_template_dns:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      state: present
      name: my_dns
      default_policy: nocache

- name: Delete a10_slb_template_dns example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Delete a10_slb_template_dns instance
    a10_slb_template_dns:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      state: absent
      name: my_dns
      default_policy: nocache