

- name: Create a10_slb_template_http_policy example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Create a10_slb_template_http_policy instance
    a10_slb_template_http_policy:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      name: my_http-policy

- name: Update a10_slb_template_http_policy example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Update a10_slb_template_http_policy instance
    a10_slb_template_http_policy:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      state: present
      name: my_http-policy

- name: Delete a10_slb_template_http_policy example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Delete a10_slb_template_http_policy instance
    a10_slb_template_http_policy:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      state: absent
      name: my_http-policy