

- name: Create a10_slb_template_virtual_port example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Create a10_slb_template_virtual_port instance
    a10_slb_template_virtual_port:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      name: default
      conn_limit: 1
      rate_interval: second
      pkt_rate_interval: second

- name: Update a10_slb_template_virtual_port example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Update a10_slb_template_virtual_port instance
    a10_slb_template_virtual_port:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      state: present
      name: default
      conn_limit: 1
      rate_interval: second
      pkt_rate_interval: second

- name: Delete a10_slb_template_virtual_port example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Delete a10_slb_template_virtual_port instance
    a10_slb_template_virtual_port:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      state: absent
      name: default
      conn_limit: 1
      rate_interval: second
      pkt_rate_interval: second