

- name: Create a10_slb_template_cipher example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Create a10_slb_template_cipher instance
    a10_slb_template_cipher:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      name: my_cipher

- name: Update a10_slb_template_cipher example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Update a10_slb_template_cipher instance
    a10_slb_template_cipher:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      state: present
      name: my_cipher

- name: Delete a10_slb_template_cipher example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Delete a10_slb_template_cipher instance
    a10_slb_template_cipher:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      state: absent
      name: my_cipher