- name: Reload Vthunder instance example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: a10_reload all
    a10_reload:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      a10_port: "{{ a10_port }}"
      a10_protocol: "{{ a10_protocol }}"
      all: 1
