- name: Reload Specific Device example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: a10_reload specific device
    a10_reload:
      state: "present"
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }} "
      a10_port: "{{ a10_port }}"
      a10_protocol: "{{ a10_protocol }}"
      device: 1
