- name: Change enable password example 
  connection: local
  hosts: all 
  tasks:
  - name: Change password for enable command
    a10_enable_password:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      a10_protocol: "{{ a10_protocol }}"
      a10_port: "{{ a10_port }}"
      password: "supersecret"
