- name: a10_cgnv6_lsn_alg_h323 Example PlayBook
  hosts: localhost
  connection: local
  tasks:
  - name: a10_cgnv6_lsn_alg_h323
    a10_cgnv6_lsn_alg_h323:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      a10_port: "{{ a10_port }}"
      a10_protocol: "{{ a10_protocol }}"
      partition: "MyPartition"
      h323_value: "enable"
      sampling_enable: 
        - counters1: "all"
