- name: a10_cgnv6_lsn_endpoint_independent_mapping_tcp Example PlayBook
  hosts: localhost
  connection: local
  tasks:
  - name: a10_cgnv6_lsn_endpoint_independent_mapping_tcp
    a10_cgnv6_lsn_endpoint_independent_mapping_tcp:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      a10_port: "{{ a10_port }}"
      a10_protocol: "{{ a10_protocol }}"
      partition: "MyPartition"
      port_list:
       - port: "8080"
         port_end: "9000"
