- hosts: all
  connection: local
  name: "My thing"
  tasks:
  - name: "Create ssl cert "
    a10_slb_template_client_ssl:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      a10_port: "{{ a10_port }}"
      a10_protocol: "{{ a10_protocol }}"
      name: client_ssl
      cert: mycert
      key: mykey
      key_passphrase:
      dh_type: 2048
