---
- name: Create rba group and add user to this group
  hosts: localhost
  connection: local
  tasks:
    - name: Create rba group and add user to this group
      a10_rba_group:
        a10_host: "{{ a10_host }}"
        a10_username: "{{ a10_username }}"
        a10_password: "{{ a10_password }}"
        a10_protocol: "{{ a10_protocol }}"
        a10_port: "{{ a10_port }}"
        user_list:
          - user: "user01" #Enter existing user
        name: "rba_group_01" #name of rba group
