- name: Request license example 
  connection: local
  hosts: all 
  tasks:
  - name: Request license
    a10_glm:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      a10_protocol: "{{ a10_protocol }}"
      a10_port: "{{ a10_port }}"
      use_mgmt_port: 0
      send:
        license-request: 1
