- name: Set glm token example 
  connection: local
  hosts: all 
  tasks:
  - name: Authenticate via token
    a10_glm:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      a10_protocol: "{{ a10_protocol }}"
      a10_port: "{{ a10_port }}"
      token: "EXAMPLE_TOKEN"
      use_mgmt_port: 0
