- name: a10_cgnv6_stateful_firewall_tcp_syn_timeout example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Create a10_cgnv6_stateful_firewall_tcp_syn_timeout
    a10_cgnv6_stateful_firewall_tcp_syn_timeout:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      a10_port: "{{ a10_port }}"
      a10_protocol: "{{ a10_protocol }}"
      partition: "MyPartition"
      syn_timeout_val: "3"
