- name: a10_cgnv6_stateful_firewall_alg_pptp example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Create a10_cgnv6_stateful_firewall_alg_pptp
    a10_cgnv6_stateful_firewall_alg_pptp:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      a10_port: "{{ a10_port }}"
      a10_protocol: "{{ a10_protocol }}"
      partition: "MyPartition"
      pptp_value: "disable"
      sampling_enable: 
        - counters1: "all"

