- name: a10_cgnv6_stateful_firewall_tcp_idle_timeout example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Create a10_cgnv6_stateful_firewall_tcp_idle_timeout
    a10_cgnv6_stateful_firewall_tcp_idle_timeout:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      a10_port: "{{ a10_port }}"
      a10_protocol: "{{ a10_protocol }}"
      partition: "MyPartition"
      port_end: "9000"
      idle_timeout_val_port_range: "500"
      port: "8000"
