- name: a10_cgnv6_stateful_firewall_endpoint_independent_filtering_udp example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Create a10_cgnv6_stateful_firewall_endpoint_independent_filtering_udp
    a10_cgnv6_stateful_firewall_endpoint_independent_filtering_udp:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      a10_port: "{{ a10_port }}"
      a10_protocol: "{{ a10_protocol }}"
      partition: "MyPartition"
      port_list:
        - port_end: "9000"
          port: "8000"
