

- name: Create a10_network_mac_address_static example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Create a10_network_mac_address_static instance
    a10_network_mac_address_static:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      mac: NO_EXAMPLE
      vlan: 2

- name: Update a10_network_mac_address_static example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Update a10_network_mac_address_static instance
    a10_network_mac_address_static:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      state: present
      mac: NO_EXAMPLE
      vlan: 2

- name: Delete a10_network_mac_address_static example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Delete a10_network_mac_address_static instance
    a10_network_mac_address_static:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      state: absent
      mac: NO_EXAMPLE
      vlan: 2