

- name: Create a10_network_arp_static example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Create a10_network_arp_static instance
    a10_network_arp_static:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      ip_addr: 10.0.0.1
      vlan: 2

- name: Update a10_network_arp_static example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Update a10_network_arp_static instance
    a10_network_arp_static:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      state: present
      ip_addr: 10.0.0.1
      vlan: 2

- name: Delete a10_network_arp_static example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Delete a10_network_arp_static instance
    a10_network_arp_static:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      state: absent
      ip_addr: 10.0.0.1
      vlan: 2