

- name: Create a10_network_bridge_vlan_group example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Create a10_network_bridge_vlan_group instance
    a10_network_bridge_vlan_group:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      bridge_vlan_group_number: 1
      forward_traffic: forward-ip-traffic

- name: Update a10_network_bridge_vlan_group example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Update a10_network_bridge_vlan_group instance
    a10_network_bridge_vlan_group:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      state: present
      bridge_vlan_group_number: 1
      forward_traffic: forward-ip-traffic

- name: Delete a10_network_bridge_vlan_group example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Delete a10_network_bridge_vlan_group instance
    a10_network_bridge_vlan_group:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      state: absent
      bridge_vlan_group_number: 1
      forward_traffic: forward-ip-traffic