

- name: Create a10_network_vlan example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Create a10_network_vlan instance
    a10_network_vlan:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      vlan_num: 2

- name: Update a10_network_vlan example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Update a10_network_vlan instance
    a10_network_vlan:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      state: present
      vlan_num: 2

- name: Delete a10_network_vlan example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Delete a10_network_vlan instance
    a10_network_vlan:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      state: absent
      vlan_num: 2