

- name: Create a10_network_lacp_passthrough example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Create a10_network_lacp_passthrough instance
    a10_network_lacp_passthrough:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      peer_from: None
      peer_to: None

- name: Update a10_network_lacp_passthrough example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Update a10_network_lacp_passthrough instance
    a10_network_lacp_passthrough:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      state: present
      peer_from: None
      peer_to: None

- name: Delete a10_network_lacp_passthrough example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Delete a10_network_lacp_passthrough instance
    a10_network_lacp_passthrough:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      state: absent
      peer_from: None
      peer_to: None