

- name: Create a10_network_bpdu_fwd_group example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Create a10_network_bpdu_fwd_group instance
    a10_network_bpdu_fwd_group:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      bpdu_fwd_group_number: 1

- name: Update a10_network_bpdu_fwd_group example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Update a10_network_bpdu_fwd_group instance
    a10_network_bpdu_fwd_group:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      state: present
      bpdu_fwd_group_number: 1

- name: Delete a10_network_bpdu_fwd_group example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Delete a10_network_bpdu_fwd_group instance
    a10_network_bpdu_fwd_group:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      state: absent
      bpdu_fwd_group_number: 1