- name: a10_cgnv6_nat46_stateless_prefix example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Create a10_cgnv6_nat46_stateless_prefix
    a10_cgnv6_nat46_stateless_prefix:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      a10_port: "{{ a10_port }}"
      a10_protocol: "{{ a10_protocol }}"
      partition: "MyPartition"
      ipv6_prefix: "2001:0DB8:0000:000b:0000:0000:0000:0001/96"
      vrid: "0"
