- name: a10_cgnv6_nat46_stateless_global example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Create a10_cgnv6_nat46_stateless_global
    a10_cgnv6_nat46_stateless_global:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      a10_port: "{{ a10_port }}"
      a10_protocol: "{{ a10_protocol }}"
      partition: "MyPartition"
      uuid: "TestCGNV6StatelessNat46Global"
      sampling_enable: 
        - counters1: "all"
