- name: a10_cgnv6_nat46_stateless_static_dest_mapping example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Create a10_cgnv6_nat46_stateless_static_dest_mapping
    a10_cgnv6_nat46_stateless_static_dest_mapping:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      a10_port: "{{ a10_port }}"
      a10_protocol: "{{ a10_protocol }}"
      partition: "MyPartition"
      count: "2"
      v6_address: "2001:0DB8:0000:000b:0000:0000:0000:0001"
      to_shared: "false"
      v4_address: "10.10.10.2"
      shared: "false"
      vrid: "0"
