
- name: Update a10_harmony_controller_profile example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Update a10_harmony_controller_profile instance
    a10_harmony_controller_profile:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      state: present
      a10_port: "{{ a10_port }}"
      a10_protocol: "{{ a10_protocol }}"
      host: "10.0.0.2" # mgmt IP
      port: "8443"     #fixed port
      user_name: "test-profile" #profile name of harmony controller
