

- name: Create a10_interface_ethernet example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Create a10_interface_ethernet instance
    a10_interface_ethernet:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      ifnum: None
      load_interval: 5
      duplexity: auto
      speed: auto
      action: disable

- name: Update a10_interface_ethernet example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Update a10_interface_ethernet instance
    a10_interface_ethernet:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      state: present
      ifnum: None
      load_interval: 5
      duplexity: auto
      speed: auto
      action: disable

- name: Delete a10_interface_ethernet example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Delete a10_interface_ethernet instance
    a10_interface_ethernet:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      state: absent
      ifnum: None
      load_interval: 5
      duplexity: auto
      speed: auto
      action: disable