

- name: Create a10_interface_trunk example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Create a10_interface_trunk instance
    a10_interface_trunk:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      ifnum: 1
      timer: 1
      action: enable

- name: Update a10_interface_trunk example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Update a10_interface_trunk instance
    a10_interface_trunk:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      state: present
      ifnum: 1
      timer: 1
      action: enable

- name: Delete a10_interface_trunk example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Delete a10_interface_trunk instance
    a10_interface_trunk:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      state: absent
      ifnum: 1
      timer: 1
      action: enable