

- name: Create a10_interface_ethernet_trunk_group example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Create a10_interface_ethernet_trunk_group instance
    a10_interface_ethernet_trunk_group:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      trunk_number: 1
      type: static
      mode: active
      timeout: long

- name: Update a10_interface_ethernet_trunk_group example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Update a10_interface_ethernet_trunk_group instance
    a10_interface_ethernet_trunk_group:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      state: present
      trunk_number: 1
      type: static
      mode: active
      timeout: long

- name: Delete a10_interface_ethernet_trunk_group example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Delete a10_interface_ethernet_trunk_group instance
    a10_interface_ethernet_trunk_group:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      state: absent
      trunk_number: 1
      type: static
      mode: active
      timeout: long