- name: Assign interface IP address
  connection: local
  hosts: localhost
  tasks:
  - name: Assign interface IP address
    a10_interface_ethernet:
      state: "{{ state }}"
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      a10_port: "{{ a10_port }}"
      a10_protocol: "{{ a10_protocol }}"
      ip:
        dhcp: "true"
      ifnum: 1
      action: enable
